import type { ProspectDetail } from "../types";

export const MOCK_PROSPECTS: ProspectDetail[] = [
  {
    id: "1",
    companyName: "Acme Corp",
    companyInitial: "A",
    avatarColor: "bg-slate-800",
    industry: "Enterprise SaaS",
    employeeRange: "500-1k",
    intentLabel: "High",
    signalCount: 8,
    signalSummary: "Recently raised $40M Series B. CTO mentioned Nitrogan on LinkedIn 2h ago.",
    timestamp: "2 min ago",
    status: "new",
    description: "Cloud Infrastructure Management & Security",
    location: "San Francisco, CA",
    websiteUrl: "acme.co",
    employeeCount: 842,
    intentScore: 94,
    signals: [
      {
        id: "s1",
        type: "expansion",
        title: "Expansion Signal",
        description:
          "Hiring 15+ DevOps Engineers across EMEA region. Estimated cloud spend increasing by 35%.",
      },
      {
        id: "s2",
        type: "executive",
        title: "Executive Interest",
        description:
          'Jane Doe (CTO) downloaded Whitepaper: "Scaling Multi-cloud Security" at 11:42 AM.',
      },
      {
        id: "s3",
        type: "technographic",
        title: "Technographic Shift",
        description:
          'Uninstalled Datadog. Currently searching for "Modern alternatives to observability stacks".',
      },
    ],
    personas: [
      {
        id: "p1",
        name: "Sarah Chen",
        role: "VP of Engineering",
        avatarUrl: null,
      },
      {
        id: "p2",
        name: "Marcus Thorne",
        role: "Director of Security",
        avatarUrl: null,
      },
    ],
    firmographics: [
      { label: "Revenue", value: "$125M+" },
      { label: "Founded", value: "2016" },
      { label: "Industry", value: "Cloud Sec" },
      { label: "Hiring", value: "Aggressive", highlight: true },
    ],
  },
  {
    id: "2",
    companyName: "Stellar Dynamics",
    companyInitial: "S",
    avatarColor: "bg-indigo-600",
    industry: "Logistics",
    employeeRange: "1k-5k",
    intentLabel: "Medium",
    signalCount: 3,
    signalSummary: "New Head of Sales appointed. Previously used competitor tool at Oracle.",
    timestamp: "45 min ago",
    status: "new",
    description: "Global Supply Chain & Logistics Solutions",
    location: "Austin, TX",
    websiteUrl: "stellardynamics.io",
    employeeCount: 2100,
    intentScore: 67,
    signals: [
      {
        id: "s4",
        type: "executive",
        title: "Leadership Change",
        description: "New Head of Sales appointed with prior experience using competitor tools at Oracle.",
      },
    ],
    personas: [
      {
        id: "p3",
        name: "David Park",
        role: "Head of Sales",
        avatarUrl: null,
      },
    ],
    firmographics: [
      { label: "Revenue", value: "$80M+" },
      { label: "Founded", value: "2012" },
      { label: "Industry", value: "Logistics" },
      { label: "Hiring", value: "Moderate" },
    ],
  },
  {
    id: "3",
    companyName: "Globex Inc",
    companyInitial: "G",
    avatarColor: "bg-orange-600",
    industry: "Manufacturing",
    employeeRange: "10k+",
    intentLabel: "High",
    signalCount: 12,
    signalSummary: "Increased web traffic to pricing page by 400% in last 24 hours.",
    timestamp: "1 hour ago",
    status: "new",
    description: "Industrial Manufacturing & Automation",
    location: "Chicago, IL",
    websiteUrl: "globex.com",
    employeeCount: 15000,
    intentScore: 88,
    signals: [
      {
        id: "s5",
        type: "expansion",
        title: "Web Traffic Surge",
        description: "Pricing page visits increased by 400% in the last 24 hours.",
      },
      {
        id: "s6",
        type: "funding",
        title: "Budget Allocation",
        description: "Q2 budget planning documents reference digital transformation initiative.",
      },
    ],
    personas: [
      {
        id: "p4",
        name: "Elena Rodriguez",
        role: "CTO",
        avatarUrl: null,
      },
    ],
    firmographics: [
      { label: "Revenue", value: "$2B+" },
      { label: "Founded", value: "1998" },
      { label: "Industry", value: "Manufacturing" },
      { label: "Hiring", value: "Aggressive", highlight: true },
    ],
  },
  {
    id: "4",
    companyName: "Vandelay Ind.",
    companyInitial: "V",
    avatarColor: "bg-emerald-600",
    industry: "Import/Export",
    employeeRange: "50-200",
    intentLabel: "Low",
    signalCount: 1,
    signalSummary: 'Job posting for "Digital Transformation Manager" matches our persona.',
    timestamp: "3 hours ago",
    status: "new",
    description: "International Trade & Distribution",
    location: "New York, NY",
    websiteUrl: "vandelay.com",
    employeeCount: 150,
    intentScore: 32,
    signals: [
      {
        id: "s7",
        type: "expansion",
        title: "Hiring Signal",
        description: '"Digital Transformation Manager" role posted, matching target buyer persona.',
      },
    ],
    personas: [
      {
        id: "p5",
        name: "Art Vandelay",
        role: "CEO",
        avatarUrl: null,
      },
    ],
    firmographics: [
      { label: "Revenue", value: "$15M" },
      { label: "Founded", value: "2005" },
      { label: "Industry", value: "Trade" },
      { label: "Hiring", value: "Low" },
    ],
  },
];
